### ISSUE TITLE
Rules composition could be made using Conducer

### ISSUE THREAD

**Issue by sebas5384** [Kikobeats/osom#13]
Hey! awesome lib!
Really lightwieght and functional too, so I was wondering, hey! osom, could be a a good fit to use with [Conducer](https://github.com/choko-org/conducer) to compose a set of rules into one.

Congrats, is nice to see simple libs like these.

**Comment by Kikobeats** [comment]
Thanks for your comment, but currently I'm happy with the current implementation 👍
